### PR TITLE
First cut at bliinding with a context string

### LINKED ISSUE #30: Make 'unblind' optional?
Our definition of key-blinding includes the unblind operation such that `Unblind( Blind( pk, bk), bk) = pk`. This suits applications where `bk` is private, but their are applications where this is not the case. Notably, the use of key-blinding in Tor has `bk` being a public value, informed by the daily consensus, and unblinding is impossible, making the blinding process more one-way. 

Should the spec include this option, and discuss that the choice reflects whether the `bk` value is private or not? This would likely also mean that multiple security models are necessary, depending on the configuration used.

### PR DESCRIPTION
**Pull request by chris-wood**
Closes #30. 

We still need to do a couple of things before this lands.

- [x] Add examples for context strings based on existing applications
- [x] Update test vectors

cc @tlepoint, @FredericJacobs

### CODE REVIEW

**Review by tlepoint — APPROVED** [review]
LGTM!

**Comment by chris-wood** [comment]
OK, test vectors updated. @jedisct1, could you please confirm interop?

**Comment by chris-wood** [comment]
@tlepoint could you please review the new text on application considerations?

**Comment by jedisct1** [comment]
Interop:

✅ Zig
✅ Rust

**Comment by tlepoint** [comment]
> @tlepoint could you please review the new text on application considerations?

Looks good, thanks for the change.

**Pull request merged**
